version: '3.1'

services:

  redis:
    container_name: hady-redis
    image: redis:5.0.4
    ports:
      - "6379:6379"
    command: ["redis-server", "--save"]

  db:
    container_name: hady-postgres
    image: postgres:11.3
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_USER: hady
      POSTGRES_DB: hady
      TZ: Asia/Singapore
    ports:
      - "5432:5432"
    volumes:
      - ../db/seeds:/docker-entrypoint-initdb.d

